import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { renderClubs, validateClubs } from './clubs.mjs';
const template = await readFile(new URL('../clubs.html', import.meta.url), 'utf8');
const fixture = {slug:'test-club',name:'Test Club',countryCode:'LK',country:'Sri Lanka',city:'Colombo',description:'Test fixture only.',status:'approved'};
const render = clubs => renderClubs({ data:{clubs},template,siteUrl:'https://example.test',today:'2026-10-03' });
const result=render([fixture,{...fixture,slug:'draft-club',status:'draft'},{...fixture,slug:'suspended-club',status:'suspended'},{...fixture,slug:'expired-club',validUntil:'2026-10-02'}]);
assert.equal(result.count,1);
assert.deepEqual(result.paths,['clubs/','clubs/countries/lk/','clubs/test-club/']);
assert(!result.pages.get('clubs/index.html').includes('draft-club'));
assert.equal(render([{...fixture,validUntil:'2026-10-03'}]).count,1);
assert.equal(render([{...fixture,validUntil:'2026-10-04'}]).count,1);
const international=render([fixture,{...fixture,slug:'second-country-club',name:'Another Country Test Club',countryCode:'GB',country:'United Kingdom',city:'London'}]);
assert(!international.pages.get('clubs/countries/lk/index.html').includes('Another Country Test Club'));
assert(international.pages.get('clubs/countries/gb/index.html').includes('Another Country Test Club'));
for(const change of [{slug:'../unsafe'},{slug:'countries'},{website:'javascript:alert(1)'},{validUntil:'2026-02-30'},{phone:'bad" onclick="x'},{countryCode:'LK/'}]) assert.throws(()=>validateClubs({clubs:[{...fixture,...change}]}));
assert.throws(()=>validateClubs({clubs:[fixture,fixture]}));
const hostile=render([{...fixture,name:'Club <script>alert(1)</script>',description:'<img src=x onerror=alert(1)>'}]);
const profile=hostile.pages.get('clubs/test-club/index.html');
assert(!profile.includes('<script>alert(1)</script>'));
assert(!profile.includes('<img src=x'));
for(const match of profile.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g))JSON.parse(match[1]);
assert(profile.includes('href="/styles.css"'));
assert(profile.includes('https://example.test/clubs/test-club/'));
assert(!profile.includes('<strong>Affiliation number:</strong>'));
assert.equal(render([]).pages.size,1);
const actual=JSON.parse((await readFile(new URL('../data/clubs.json',import.meta.url),'utf8')).replace(/^\uFEFF/,''));
const published=renderClubs({data:actual,template,siteUrl:'https://www.mmasrilanka.com'});
assert(published.pages.get('clubs/mma-colombo-combat-club/index.html').includes('tel:+94753414414'));
console.log('Passed: affiliation publication rules, country isolation, unsafe input rejection, escaping, structured data, nested assets, empty directory and supplied club phone.');
